# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to server

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: web.blbt.app
        username: team1
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "dist"
        target: "."
        
    - name: Restarting Server
      uses: appleboy/ssh-action@master
      with:
        host: web.blbt.app
        username: team1
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          pm2 stop all
          pm2 del all
          pm2 start "java -jar build/libs/yourapartment.jar"
          pm2 start "serve dist"
